version: '3'
services:
  lyttle-rstudio:
    environment:
      - USER=rstudio
      - PASSWORD=<your-pass-word-here>
    image: "lyttle/rmark"
    build: ./lyttle_rmark
    ports:
      - 8787:8787
    volumes:
      - ./code:/home/rstudio/kitematic/sample
