version: '3'
services:
  lyttle-rstudio:
    environment:
      - USER=rstudio
      - PASSWORD=<your-pass-word-here>
      - GPG_KEYS=B215C1633BCA0477615F1B35A5B3A004745C015A     B3C42148A44E6983B3E4CC0793FA9B1AB75C61B8     90AA470469D3965A87A5DCB494D03953902C9419     80F98B2E0DAB6C8281BDF541A7C8C3B2F71EDF1C     7F74F97C103468EE5D750B583AB00996FC26A641     33C235A34C46AA3FFB293709A328C3A2C3C45C06
      - GCC_MIRRORS=https://ftpmirror.gnu.org/gcc         https://bigsearcher.com/mirrors/gcc/releases         https://mirrors-usa.go-parts.com/gcc/releases     https://mirrors.concertpass.com/gcc/releases         http://www.netgull.com/gcc/releases
      - GCC_VERSION=7.4.0
    #image: "lyttle/rstudio"
    build: ./fortran
    ports:
      - 8787:8787
    volumes:
      - .:/home/rstudio/kitematic/lyttleR
